name: LunaChatBridge
version: ${project.version}
main: com.github.lazygon.lunachatbridge.bukkit.BukkitMain
author: lazy_gon
depend: ["LunaChat"]

permissions:
  lunachatbridge.tell:
    description: サーバー間でtell、replyコマンドを貫通させるための権限。
    default: true